[project]
name = "nano-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.14"
dependencies = [
	"easyocr",
	"einops>=0.7.0",
	"mss>=10.2.0",
	"numpy",
	"opencv-python>=4.8.0",
	"pillow",
	"pyautogui",
	"pynput>=1.7.6",
	"pyyaml>=6.0",
	"scipy>=1.11.0",
	"timm>=0.9.0",
	"torch",
	"torchaudio",
	"torchvision",
	"ultralytics",
]

[project.optional-dependencies]
render = [
	"matplotlib>=3.8.0",
]
train = [
	"wandb>=0.19.0",
]

[tool.uv.sources]
torch = [
	{ index = "pytorch-cu118", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchaudio = [
	{ index = "pytorch-cu118", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchvision = [
	{ index = "pytorch-cu118", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]

[[tool.uv.index]]
name = "pytorch-cu118"
url = "https://download.pytorch.org/whl/cu118"
explicit = true
